use enum_dispatch::enum_dispatch;

use crate::markers::{
    chapters_verses::{c::C, ca::CA, cd::CD, cl::CL, cp::CP, v::V, va::VA, vp::VP},
    cross_references::{
        rq::RQ, x::X, xdc::XDC, xk::XK, xnt::XNT, xo::XO, xop::XOP, xot::XOT, xq::XQ, xt::XT,
        xta::XTA,
    },
    footnotes::{
        f::F, fdc::FDC, fe::FE, fk::FK, fl::FL, fm::FM, fp::FP, fq::FQ, fqa::FQA, fr::FR, ft::FT,
        fv::FV, fw::FW,
    },
    identification::{
        header::H, id::ID, ide::IDE, rem::REM, sts::STS, toc::TOC, toca::TOCA, usfm::USFM,
    },
    introductions::{
        ib::IB, ie::IE, iex::IEX, ili::ILI, im::IM, imi::IMI, imq::IMQ, imt::IMT, imte::IMTE,
        io::IO, ior::IOR, iot::IOT, ip::IP, ipi::IPI, ipq::IPQ, ipr::IPR, iq::IQ, iqt::IQT, is::IS,
    },
    lists::{
        lf::LF,
        lh::LH,
        li::LI,
        lim::LIM,
        litl::LITL,
        structured_list_entries::{lik::LIK, liv::LIV},
    },
    paragraphs::{
        b::B, cls::CLS, m::M, mi::MI, nb::NB, p::P, pc::PC, ph::PH, pi::PI, pm::PM, pmc::PMC,
        pmo::PMO, pmr::PMR, po::PO, pr::PR,
    },
    poetry::{b::B as PoetryB, q::Q, qa::QA, qac::QAC, qc::QC, qd::QD, qm::QM, qr::QR, qs::QS},
    tables::{tc::TC, tcr::TCR, th::TH, thr::THR, tr::TR},
    titles_headings_labels::{
        d::D, mr::MR, ms::MS, mt::MT, mte::MTE, r::R, rq::RQ as HeadingRQ, s::S, sd::SD, sp::SP,
        sr::SR,
    },
    words_and_characters::{
        character_styling::{bd::BD, bdit::BDIT, em::EM, it::IT, no::NO, sc::SC, sup::SUP},
        spacing_and_breaks::{double_forward_slash::DoubleForwardSlash, pb::PB, tilde::Tilde},
        special_features::{fig::FIG, ndx::NDX, pro::PRO, rb::RB, w::W, wa::WA, wg::WG, wh::WH},
        special_text::{
            add::ADD, addpn::ADDPN, bk::BK, dc::DC, k::K, lit::LIT, nd::ND, ord::ORD, pn::PN,
            png::PNG, qt::QT, sig::SIG, sls::SLS, tl::TL, wj::WJ,
        },
    },
};

#[enum_dispatch]
pub enum AnyMarker {
    ADD,
    ADDPN,
    B,
    PoetryB,
    BD,
    BDIT,
    BK,
    C,
    CA,
    CD,
    CL,
    CLS,
    CP,
    D,
    DC,
    DoubleForwardSlash,
    EM,
    F,
    FDC,
    FE,
    FIG,
    FK,
    FL,
    FM,
    FP,
    FQ,
    FQA,
    FR,
    FT,
    FV,
    FW,
    H,
    IB,
    ID,
    IDE,
    IE,
    IEX,
    ILI,
    IM,
    IMI,
    IMQ,
    IMT,
    IMTE,
    IO,
    IOR,
    IOT,
    IP,
    IPI,
    IPQ,
    IPR,
    IQ,
    IQT,
    IS,
    IT,
    K,
    LF,
    LH,
    LI,
    LIK,
    LIM,
    LIT,
    LITL,
    LIV,
    M,
    MI,
    MR,
    MS,
    MT,
    MTE,
    NB,
    ND,
    NDX,
    NO,
    ORD,
    P,
    PB,
    PC,
    PH,
    PI,
    PM,
    PMC,
    PMO,
    PMR,
    PN,
    PNG,
    PO,
    PR,
    PRO,
    Q,
    QA,
    QAC,
    QC,
    QD,
    QM,
    QR,
    QS,
    QT,
    R,
    RB,
    REM,
    RQ,
    HeadingRQ,
    S,
    SC,
    SD,
    SIG,
    SLS,
    SP,
    SR,
    STS,
    SUP,
    TC,
    TCR,
    TH,
    THR,
    TL,
    TOC,
    TOCA,
    TR,
    Tilde,
    USFM,
    V,
    VA,
    VP,
    W,
    WA,
    WG,
    WH,
    WJ,
    X,
    XDC,
    XK,
    XNT,
    XO,
    XOP,
    XOT,
    XQ,
    XT,
    XTA,
}
